// ============================================================================
// MAAD.md Generator
// Generates the LLM instruction file for a MAAD project.
// Content is STABLE — no volatile counts, no project-state details.
// Regenerated on every reindex so interface changes propagate.
// ============================================================================

import type { Registry, SchemaStore, BackendStats } from './types.js';

export interface MaadMdContext {
  projectRoot: string;
  enginePath: string;
  registry: Registry;
  schemaStore: SchemaStore;
  stats: BackendStats | null;
}

export function generateMaadMd(ctx: MaadMdContext): string {
  const cmd = buildCmdPrefix(ctx.enginePath, ctx.projectRoot);
  const sections: string[] = [];

  sections.push(generateHeader(cmd));
  sections.push(generateQuickStart(cmd, ctx));
  sections.push(generateFullCommandRef(cmd));
  sections.push(generatePrimitives());
  sections.push(generateRules());
  sections.push(generateCompositionPatterns(cmd));
  sections.push(generateFeedback());

  return sections.join('\n\n---\n\n') + '\n';
}

function buildCmdPrefix(enginePath: string, projectRoot: string): string {
  return `node ${enginePath} --project ${projectRoot}`;
}

// ---- Sections -------------------------------------------------------------

function generateHeader(cmd: string): string {
  return `# MAAD.md — LLM Interface

> Auto-generated by the MAAD engine. Do not edit.
>
> **This is a test/evaluation project.** If you find issues or have improvement ideas,
> create a feedback file: \`feedback-YYYY-MM-DD-<model>.md\` (e.g. \`feedback-2026-04-07-gpt-5.md\`).

## What is this?

A **MAAD project** — a markdown-native database. Markdown files are the records. A queryable index gives you structured access without reading full files.

**This file** = stable operating instructions. Read once per session.
**\`maad_summary\` tool** = live project snapshot. Run once per session to see what's here.
**SCHEMA.md** = deep structural reference. Read only when \`maad_schema\` isn't enough.

## How to access data

Use **MAAD MCP tools** for all data operations. Do not use shell commands or direct file reads for data access. If \`maad_summary\` reports an empty project, read \`_skills/architect-core.md\` and enter Architect mode to design and deploy the schema.

If using CLI for debugging:
\`\`\`
${cmd} <command> [args]
\`\`\``;
}

function generateQuickStart(cmd: string, _ctx: MaadMdContext): string {
  return `## Boot Sequence

**1. You just read this file.** You now know the commands.

**2. Run \`summary\` to see what's in this project:**
\`\`\`
${cmd} summary
\`\`\`
Returns: types + counts, sample doc_ids, extracted object inventory.

That's it. You're oriented. Now use the commands below as needed.

### Reading data
- \`get <doc_id> hot\` — frontmatter only (cheapest)
- \`get <doc_id> full\` — resolved record: refs, objects, related docs
- \`get <doc_id> warm <block_id>\` — frontmatter + one section
- \`get <doc_id> cold\` — full file (expensive, use sparingly)

### Before writing
- \`schema <type>\` — field definitions, required fields, enum values

### Reference (not needed for boot)
- **SCHEMA.md** has full field-level detail for every type. Read it when \`schema <type>\` isn't enough.
- **\`audit\`** shows recent git activity if you need project history.`;
}

function generateFullCommandRef(cmd: string): string {
  return `## All Commands

> Commands shown below in CLI form for explicit syntax. **MCP tool names prefix \`maad_\`** (e.g. \`get\` → \`maad_get\`, \`bulk_create\` → \`maad_bulk_create\`). Agent workflows use the MCP variants; CLI is for operator debugging.

### Discover
| Command | What it does |
|---------|-------------|
| \`scan <file.md>\` | Structural analysis of a raw file (no registry needed) |
| \`scan <dir/>\` | Corpus-level patterns: recurring fields, headings, document families |
| \`summary\` | **Start here.** Types, counts, sample IDs, object inventory |

### Read
| \`describe\` | Project overview: types, doc counts, primitives |
| \`get <doc_id> hot\` | Frontmatter only (cheapest read) |
| \`get <doc_id> warm <block>\` | Frontmatter + one section |
| \`get <doc_id> cold\` | Full document (expensive — use sparingly) |
| \`get <doc_id> full\` | Resolved record: refs resolved, objects, related, latest note |
| \`query <type>\` | All documents of a type |
| \`query <type> --filter field=value\` | Filtered (ops: eq, neq, gt, gte, lt, lte, in, contains) |
| \`query <type> --fields name,status\` | Return frontmatter fields in results (projection) |
| \`search <primitive>\` | Cross-document object search |
| \`search <primitive> --subtype <s>\` | Filter by subtype (e.g. person, attorney) |
| \`search <primitive> --query <text>\` | Substring match on values (alias: --contains) |
| \`related <doc_id> both\` | All connected documents (outgoing + incoming) |
| \`related <doc_id> outgoing\` | Documents this one references |
| \`related <doc_id> incoming\` | Documents that reference this one |
| \`schema <type>\` | Field definitions, ID prefix, format hints (use before writes) |
| \`aggregate\` | Group by a field with count/sum/avg/min/max. **Use instead of iterating records to compute totals.** Supports multi-hop ref chains (\`a->b->c\`) for cross-doctype aggregates. Filters accept \`between\` shortcut and array-of-ops (AND). |
| \`join\` | Query + follow refs + project fields from both sides in one call. **Use instead of \`query\` → \`get\` → \`get\` chains.** |
| \`verify mode=field\` | Fact-check a field value: grounded true/false + actual value + source |
| \`verify mode=count\` | Fact-check a document count: grounded true/false + actual count |
| \`changes_since <cursor>\` | Delta feed — records modified since cursor. Opaque base64url cursor, stable order on (updated_at ASC, doc_id ASC). Empty cursor = from the beginning. |

### Write
| Command | What it does |
|---------|-------------|
| \`create <type> --field k=v [--field k=v ...] [--body "text"] [--id custom-id]\` | Create a new record |
| \`update <doc_id> --field k=v [--field k=v ...]\` | Update frontmatter fields |
| \`update <doc_id> --append "text"\` | Append to document body |
| \`update <doc_id> --body "text"\` | Replace document body |
| \`bulk_create\` | Create multiple records in one call (MCP only) |
| \`bulk_update\` | Update multiple records in one call (MCP only) |
| \`delete <doc_id>\` | Remove a record (soft by default, \`--hard\` for hard delete) |

### Maintain
| Command | What it does |
|---------|-------------|
| \`validate\` | Validate all documents against schemas |
| \`validate <doc_id>\` | Validate one document |
| \`reindex --force\` | Rebuild the full index from markdown |
| \`reload\` | Reload registry + schemas without restart (after editing \`_registry/\` or \`_schema/\`) |
| \`health\` | Engine status — write queue depth, last write op, disk headroom, git clean flag, transport + session telemetry |
| \`parse <file.md>\` | Parse one file, show structure |

### Audit (requires git)
| Command | What it does |
|---------|-------------|
| \`history <doc_id>\` | Change history for a document |
| \`audit\` | Project-wide activity |
| \`audit --since <date>\` | Activity since a date |

### Field syntax for create/update
- String: \`--field name=Acme Corp\`
- Enum: \`--field status=open\`
- Ref: \`--field client=cli-acme\`
- Array: \`--field tags=[enterprise,priority]\`
- Date: \`--field opened_at=2026-04-07\``;
}

function generatePrimitives(): string {
  return `## Extraction Primitives

Inline annotations in markdown body use \`[[type:value|label]]\` syntax. The engine extracts and indexes them.

| Primitive | Captures | Search example |
|-----------|----------|---------------|
| \`entity\` | person, org, team, product | \`search entity --subtype person\` |
| \`date\` | date, datetime | \`search date --contains 2026\` |
| \`duration\` | time span (3 hours, 2 weeks) | \`search duration\` |
| \`amount\` | currency (100.00 USD, $500) | \`search amount\` |
| \`measure\` | value + unit (500mg, 6 feet) | \`search measure\` |
| \`quantity\` | bare count (42, 1800) | \`search quantity\` |
| \`percentage\` | ratio (15%, 0.85) | \`search percentage\` |
| \`location\` | place, address | \`search location\` |
| \`identifier\` | case number, invoice, code | \`search identifier\` |
| \`contact\` | email, phone, URL | \`search contact\` |
| \`media\` | image, video, audio, document | \`search media\` |`;
}

function generateRules(): string {
  return `## Rules

1. **Run \`summary\` first** in every new session — one call to orient
2. **Use \`hot\` reads by default** — escalate to \`full\`, \`warm\`, then \`cold\` only when needed
3. **Use \`schema <type>\` before writes** — know what fields are required
4. **Use MAAD MCP tools for writes** — never edit markdown files directly; CLI forms above are for operator debugging only
5. **Use \`search\` for cross-document queries** — don't open files to find people/dates/amounts
6. **Use \`related\` for graph traversal** — don't manually search for connected docs
7. **Cite \`doc_id\` and \`block_id\`** in answers for traceability
8. **\`reindex --force\`** recovers from any stale state
9. **Inspect \`_meta.warnings[]\` on write responses** — the engine surfaces soft-validation signals (precision drift, deprecation hints) alongside successful writes. Agents self-correct on warnings, not just on errors
10. **Use \`aggregate\` for group-by totals** — don't iterate records to compute counts, sums, averages, mins, or maxes. One \`aggregate\` call with \`metric\` + \`groupBy\` returns the answer; use the \`a->b->c\` ref-chain form for cross-doctype groupings.
11. **Use \`join\` to follow refs in one call** — don't chain \`query\` → \`get\` → \`get\` to collect related fields. \`join\` projects fields from both sides of a ref in one pass.

## Grounding Rules (CRITICAL)

**Never state a number, date, amount, count, or ID from memory.** Always query first.

- Before reporting a field value → call \`get\` or \`verify\` with the doc_id and field
- Before reporting a count → call \`verify\` in count mode or \`query\` with the type and filters
- Before reporting a relationship → call \`related\` or \`join\`
- If you cannot ground a claim from the database → say "unable to verify from records"

Use \`maad_verify\` to fact-check before answering:
- \`verify mode=field docId=cas-001 field=claim_amount expected="1500000.00 USD"\`
- \`verify mode=count docType=case expectedCount=12 filters={status: "open"}\`

**The pattern:** query or verify → confirm grounded → then answer. Never the reverse.`;
}

function generateCompositionPatterns(cmd: string): string {
  return `## Composition Patterns

These are common multi-step operations built from primitives. The engine does not provide these as single commands — you compose them.

### Deep inspect (full engine internals for a document)
\`\`\`
${cmd} get <doc_id> hot          # frontmatter + metadata
${cmd} validate <doc_id>         # schema validation state
${cmd} related <doc_id> both     # all relationships
${cmd} search entity --doc <doc_id>  # all extracted objects
\`\`\`

### Onboard raw files (bootstrap a new project)
\`\`\`
${cmd} scan <directory>           # corpus-level patterns
# Read the output, then:
# 1. Create _registry/object_types.yaml with detected families
# 2. Create _schema/*.yaml with detected field patterns
# 3. Add frontmatter to each file
${cmd} reindex --force            # build the index
${cmd} summary                    # confirm orientation
\`\`\``;
}

function generateFeedback(): string {
  return `## Feedback

This is a test/evaluation project. If you encounter issues, friction, or have improvement suggestions:

1. Create a file in the project root: \`feedback-YYYY-MM-DD-<model>.md\`
   - Example: \`feedback-2026-04-07-gpt-5.md\`
   - Example: \`feedback-2026-04-08-claude-opus.md\`
2. Structure your feedback with:
   - **Observations** — what happened, what you expected
   - **Suggestions** — how to improve it
   - **Context** — what you were trying to do when the issue occurred
3. Do not modify existing feedback files from other models`;
}

export function generateStubMaadMd(enginePath: string, projectRoot: string): string {
  const cmd = buildCmdPrefix(enginePath, projectRoot);
  return `# MAAD.md — LLM Interface

> Auto-generated by the MAAD engine.
> Run \`reindex\` after adding types and schemas to update this file.
>
> **This is a test/evaluation project.** If you find issues, create a feedback file:
> \`feedback-YYYY-MM-DD-<model>.md\`

This is a **MAAD project** — a markdown-native database.

## Getting Started

1. Define types in \`_registry/object_types.yaml\`
2. Create schemas in \`_schema/\`
3. Add markdown records
4. Run: \`${cmd} reindex --force\`

This file will be regenerated with full type/command reference after the first reindex.
`;
}
