// ============================================================================
// MAAD.md Generator
// Generates the LLM instruction file for a MAAD project.
// Updated on init and reindex to reflect current registry and schemas.
// ============================================================================

import type { Registry, SchemaStore, BackendStats } from './types.js';

export interface MaadMdContext {
  projectRoot: string;
  enginePath: string;
  registry: Registry;
  schemaStore: SchemaStore;
  stats: BackendStats | null;
}

export function generateMaadMd(ctx: MaadMdContext): string {
  const cmd = buildCmdPrefix(ctx.enginePath, ctx.projectRoot);
  const sections: string[] = [];

  sections.push(generateHeader(cmd));
  sections.push(generateQuickStart(cmd, ctx));
  sections.push(generateFullCommandRef(cmd));
  sections.push(generatePrimitives());
  sections.push(generateRules());
  sections.push(generateFeedback());

  return sections.join('\n\n---\n\n') + '\n';
}

function buildCmdPrefix(enginePath: string, projectRoot: string): string {
  return `node ${enginePath} --project ${projectRoot}`;
}

// ---- Sections -------------------------------------------------------------

function generateHeader(cmd: string): string {
  return `# MAAD.md — LLM Interface

> Auto-generated by the MAAD engine. Regenerated on \`reindex\`. Do not edit.
>
> **This is a test/evaluation project.** If you find issues or have improvement ideas,
> create a feedback file: \`feedback-YYYY-MM-DD-<model>.md\` (e.g. \`feedback-2026-04-07-gpt-5.md\`).

## What is this?

A **MAAD project** — a markdown-native database. Markdown files are the records. A queryable index gives you structured access without reading full files.

**This file** = tool knowledge (commands, syntax, workflow). Read once per session.
**SCHEMA.md** = data knowledge (types, fields, doc counts). Read to understand what's in this project.

## How to run commands

\`\`\`
${cmd} <command> [args]
\`\`\`

All output is JSON unless noted.`;
}

function generateQuickStart(cmd: string, _ctx: MaadMdContext): string {
  return `## Quick Start (do this first)

**Step 1 — Orient yourself (one call):**
\`\`\`
${cmd} summary
\`\`\`
Returns: types + counts, sample doc_ids, extracted object inventory, recent activity.

**Step 2 — Read a record:**
\`\`\`
${cmd} get <doc_id> hot
\`\`\`

**Step 3 — Get a fully resolved record (refs resolved, objects, related):**
\`\`\`
${cmd} get <doc_id> full
\`\`\`

**Step 4 — Read a specific section:**
\`\`\`
${cmd} get <doc_id> warm <block_id>
\`\`\`

**Step 5 — Before writing, check what fields a type needs:**
\`\`\`
${cmd} schema <type>
\`\`\`

Most questions can be answered from steps 1-3 without a full file read.`;
}

function generateFullCommandRef(cmd: string): string {
  return `## All Commands

### Read
| Command | What it does |
|---------|-------------|
| \`summary\` | **Start here.** Types, counts, sample IDs, object inventory, activity |
| \`describe\` | Project overview: types, doc counts, primitives |
| \`get <doc_id> hot\` | Frontmatter only (cheapest read) |
| \`get <doc_id> warm <block>\` | Frontmatter + one section |
| \`get <doc_id> cold\` | Full document (expensive — use sparingly) |
| \`get <doc_id> full\` | Resolved record: refs resolved, objects, related, latest note |
| \`query <type>\` | All documents of a type |
| \`query <type> --filter field=value\` | Filtered by indexed field |
| \`search <primitive>\` | Cross-document object search |
| \`search <primitive> --subtype <s>\` | Filter by subtype (e.g. person, attorney) |
| \`search <primitive> --contains <text>\` | Substring match on values |
| \`related <doc_id> both\` | All connected documents (outgoing + incoming) |
| \`related <doc_id> outgoing\` | Documents this one references |
| \`related <doc_id> incoming\` | Documents that reference this one |
| \`inspect <doc_id>\` | Full engine internals: blocks, objects, relationships, validation |
| \`schema <type>\` | Field definitions for a type (what to pass to create/update) |

### Write
| Command | What it does |
|---------|-------------|
| \`create <type> --field k=v [--field k=v ...] [--body "text"] [--id custom-id]\` | Create a new record |
| \`update <doc_id> --field k=v [--field k=v ...]\` | Update frontmatter fields |
| \`update <doc_id> --append "text"\` | Append to document body |
| \`update <doc_id> --body "text"\` | Replace document body |

### Maintain
| Command | What it does |
|---------|-------------|
| \`validate\` | Validate all documents against schemas |
| \`validate <doc_id>\` | Validate one document |
| \`reindex --force\` | Rebuild the full index from markdown |
| \`parse <file.md>\` | Parse one file, show structure |

### Audit (requires git)
| Command | What it does |
|---------|-------------|
| \`history <doc_id>\` | Change history for a document |
| \`audit\` | Project-wide activity |
| \`audit --since <date>\` | Activity since a date |

### Field syntax for create/update
- String: \`--field name=Acme Corp\`
- Enum: \`--field status=open\`
- Ref: \`--field client=cli-acme\`
- Array: \`--field tags=[enterprise,priority]\`
- Date: \`--field opened_at=2026-04-07\``;
}

function generatePrimitives(): string {
  return `## Extraction Primitives

Inline annotations in markdown body use \`[[type:value|label]]\` syntax. The engine extracts and indexes them.

| Primitive | Captures | Search example |
|-----------|----------|---------------|
| \`entity\` | person, org, team, product | \`search entity --subtype person\` |
| \`date\` | date, datetime | \`search date --contains 2026\` |
| \`duration\` | time span (3 hours, 2 weeks) | \`search duration\` |
| \`amount\` | currency (100.00 USD, $500) | \`search amount\` |
| \`measure\` | value + unit (500mg, 6 feet) | \`search measure\` |
| \`quantity\` | bare count (42, 1800) | \`search quantity\` |
| \`percentage\` | ratio (15%, 0.85) | \`search percentage\` |
| \`location\` | place, address | \`search location\` |
| \`identifier\` | case number, invoice, code | \`search identifier\` |
| \`contact\` | email, phone, URL | \`search contact\` |
| \`media\` | image, video, audio, document | \`search media\` |`;
}

function generateRules(): string {
  return `## Rules

1. **Run \`summary\` first** in every new session — one call to orient
2. **Use \`hot\` reads by default** — escalate to \`full\`, \`warm\`, then \`cold\` only when needed
3. **Use \`schema <type>\` before writes** — know what fields are required
4. **Use the CLI for writes** — never edit markdown files directly
5. **Use \`search\` for cross-document queries** — don't open files to find people/dates/amounts
6. **Use \`related\` for graph traversal** — don't manually search for connected docs
7. **Cite \`doc_id\` and \`block_id\`** in answers for traceability
8. **\`reindex --force\`** recovers from any stale state`;
}

function generateFeedback(): string {
  return `## Feedback

This is a test/evaluation project. If you encounter issues, friction, or have improvement suggestions:

1. Create a file in the project root: \`feedback-YYYY-MM-DD-<model>.md\`
   - Example: \`feedback-2026-04-07-gpt-5.md\`
   - Example: \`feedback-2026-04-08-claude-opus.md\`
2. Structure your feedback with:
   - **Observations** — what happened, what you expected
   - **Suggestions** — how to improve it
   - **Context** — what you were trying to do when the issue occurred
3. Do not modify existing feedback files from other models`;
}

export function generateStubMaadMd(enginePath: string, projectRoot: string): string {
  const cmd = buildCmdPrefix(enginePath, projectRoot);
  return `# MAAD.md — LLM Interface

> Auto-generated by the MAAD engine.
> Run \`reindex\` after adding types and schemas to update this file.
>
> **This is a test/evaluation project.** If you find issues, create a feedback file:
> \`feedback-YYYY-MM-DD-<model>.md\`

This is a **MAAD project** — a markdown-native database.

## Getting Started

1. Define types in \`_registry/object_types.yaml\`
2. Create schemas in \`_schema/\`
3. Add markdown records
4. Run: \`${cmd} reindex --force\`

This file will be regenerated with full type/command reference after the first reindex.
`;
}
