// ============================================================================
// MAAD.md Generator
// Generates the LLM instruction file for a MAAD project.
// Updated on init and reindex to reflect current registry and schemas.
// ============================================================================

import type { Registry, SchemaStore, SchemaDefinition, FieldDefinition, BackendStats } from './types.js';

export interface MaadMdContext {
  projectRoot: string;
  enginePath: string;
  registry: Registry;
  schemaStore: SchemaStore;
  stats: BackendStats | null;
}

export function generateMaadMd(ctx: MaadMdContext): string {
  const sections: string[] = [];

  sections.push(generateHeader());
  sections.push(generateCommands(ctx.enginePath, ctx.projectRoot));
  sections.push(generateWorkflow());
  sections.push(generateTypes(ctx.registry, ctx.schemaStore, ctx.stats));
  sections.push(generatePrimitives());
  sections.push(generateRules());

  return sections.join('\n\n---\n\n') + '\n';
}

function generateHeader(): string {
  return `# MAAD.md — LLM Interface Instructions

> This file is auto-generated by the MAAD engine. Do not edit manually.
> It is regenerated on \`maad init\` and \`maad reindex\`.

This is a **MAAD project** — a markdown-native database where markdown files are the canonical records and a queryable index gives you fast, structured access.

**Do not edit markdown files directly.** Use the MAAD CLI commands below. They validate against schemas, maintain the index, and auto-commit to git.`;
}

function generateCommands(enginePath: string, projectRoot: string): string {
  const cmd = `node ${enginePath} --project ${projectRoot}`;

  return `## Commands

All commands follow: \`${cmd} <command> [args]\`

### Discovery (start here)
| Command | What it does |
|---------|-------------|
| \`describe\` | Show all registered types, doc counts, and extraction primitives |
| \`get <doc_id> hot\` | Read frontmatter only (minimal tokens) |
| \`get <doc_id> warm <block>\` | Read frontmatter + a specific section |
| \`get <doc_id> cold\` | Read the full document (use sparingly) |

### Query & Search
| Command | What it does |
|---------|-------------|
| \`query <type>\` | Find all documents of a type |
| \`query <type> --filter field=value\` | Find documents matching a filter |
| \`search <primitive>\` | Search extracted objects across all documents |
| \`search <primitive> --subtype <s>\` | Filter by subtype (e.g. \`--subtype person\`) |
| \`search <primitive> --contains <text>\` | Substring search on values |
| \`related <doc_id> both\` | Show all documents related to this one |
| \`related <doc_id> outgoing\` | Documents this one references |
| \`related <doc_id> incoming\` | Documents that reference this one |

### Maintenance
| Command | What it does |
|---------|-------------|
| \`validate\` | Validate all documents against their schemas |
| \`validate <doc_id>\` | Validate a single document |
| \`reindex --force\` | Rebuild the entire index from markdown |
| \`parse <file.md>\` | Parse a single file and show extracted structure |

### Audit (requires git)
| Command | What it does |
|---------|-------------|
| \`history <doc_id>\` | Show change history for a document |
| \`audit\` | Show project-wide activity |
| \`audit --since <date>\` | Activity since a specific date |`;
}

function generateWorkflow(): string {
  return `## Workflow

Follow this pattern for every interaction:

1. **\`describe\`** first — learn what types and data exist
2. **\`query\` or \`search\`** to find relevant documents — never guess doc_ids
3. **\`get ... hot\`** for metadata — use this for most questions
4. **\`get ... warm <block>\`** for a specific section — only when you need narrative detail
5. **\`get ... cold\`** for the full document — only when hot/warm aren't enough
6. **\`related\`** to traverse connections — walk the relationship graph, don't scan files

**Token efficiency rule:** Always start at hot. Escalate to warm only if needed. Escalate to cold only as a last resort. Most questions can be answered from hot reads alone.`;
}

function generateTypes(registry: Registry, schemaStore: SchemaStore, stats: BackendStats | null): string {
  if (registry.types.size === 0) {
    return `## Types

No types registered yet. Define types in \`_registry/object_types.yaml\` and create schemas in \`_schema/\`.`;
  }

  const lines: string[] = ['## Registered Types\n'];

  for (const [, regType] of registry.types) {
    const count = stats?.documentCountByType[regType.name as string] ?? 0;
    const schema = schemaStore.getSchemaForType(regType.name);

    lines.push(`### \`${regType.name as string}\` (${count} docs)`);
    lines.push(`- **Path:** \`${regType.path}\``);
    lines.push(`- **ID prefix:** \`${regType.idPrefix}\``);
    lines.push(`- **Schema:** \`${regType.schemaRef as string}\``);

    if (schema) {
      lines.push(`- **Required fields:** ${schema.required.join(', ')}`);

      if (schema.fields.size > 0) {
        lines.push('- **Fields:**');
        for (const [name, field] of schema.fields) {
          lines.push(`  - \`${name}\`: ${formatFieldType(field)}`);
        }
      }
    }

    lines.push('');
  }

  // Custom extraction subtypes
  if (Object.keys(registry.extraction.subtypes).length > 0) {
    lines.push('### Custom Extraction Subtypes\n');
    for (const [subtype, primitive] of Object.entries(registry.extraction.subtypes)) {
      lines.push(`- \`${subtype}\` -> \`${primitive}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function formatFieldType(field: FieldDefinition): string {
  let desc = field.type as string;
  if (field.type === 'enum' && field.values) {
    desc += ` [${field.values.join(', ')}]`;
  }
  if (field.type === 'ref' && field.target) {
    desc += ` -> ${field.target as string}`;
  }
  if (field.type === 'list' && field.itemType) {
    desc += ` of ${field.itemType}`;
    if (field.target) desc += ` -> ${field.target as string}`;
  }
  if (field.index) desc += ' (indexed)';
  if (field.role) desc += ` [role: ${field.role}]`;
  return desc;
}

function generatePrimitives(): string {
  return `## Extraction Primitives

These are the object types the engine extracts from inline \`[[type:value|label]]\` annotations:

| Primitive | What it captures | Example |
|-----------|-----------------|---------|
| \`entity\` | Person, org, team, product, event | \`[[person:Jane Smith|Jane]]\` |
| \`date\` | Date or datetime | \`[[date:2026-03-28|March 28]]\` |
| \`duration\` | Time span | \`[[duration:3 hours|three hours]]\` |
| \`amount\` | Currency value | \`[[amount:100.00 USD|$100]]\` |
| \`measure\` | Value with unit | \`[[measure:500mg|500mg]]\` |
| \`quantity\` | Bare count | \`[[quantity:42|forty-two]]\` |
| \`percentage\` | Ratio | \`[[percentage:15%|15 percent]]\` |
| \`location\` | Place or address | \`[[location:415 Elm St|415 Elm]]\` |
| \`identifier\` | Lookup key (case number, invoice) | \`[[identifier:INV-001|Invoice 1]]\` |
| \`contact\` | Email, phone, URL | \`[[email:jane@acme.com|Jane's email]]\` |
| \`media\` | File reference (image, video, doc) | \`[[image:photo.jpg|evidence photo]]\` |

Search any primitive: \`search entity --subtype person\`, \`search amount\`, \`search date --contains 2026\``;
}

function generateRules(): string {
  return `## Rules

1. **Never edit markdown files directly** — use CLI commands for all writes
2. **Always \`describe\` first** in a new session to understand the project state
3. **Prefer hot reads** — most questions are answerable from frontmatter alone
4. **Use \`related\` for graph traversal** — don't manually search for connected docs
5. **Validate before committing** — run \`validate\` to catch schema violations
6. **Use \`search\` for cross-document queries** — find people, dates, amounts across all records without opening files
7. **Cite doc_ids and block_ids** — when referencing data, include the source for traceability
8. **\`reindex --force\` recovers from any stale state** — the index is always rebuildable from markdown`;
}

export function generateStubMaadMd(enginePath: string, projectRoot: string): string {
  return `# MAAD.md — LLM Interface Instructions

> This file is auto-generated by the MAAD engine.
> Run \`maad reindex\` after adding types and schemas to update this file.

This is a **MAAD project** — a markdown-native database.

## Getting Started

1. Define types in \`_registry/object_types.yaml\`
2. Create schemas in \`_schema/\`
3. Add markdown records
4. Run: \`node ${enginePath} reindex --project ${projectRoot}\`

This file will be regenerated with full type information and command reference after the first reindex.
`;
}
